### ISSUE TITLE
st2express is missing from hosts file on st2express

### ISSUE THREAD

**Issue by lattwood** [StackStorm/st2workroom#111]
```
vagrant@st2express:~$ st2 --debug action list
ERROR: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

CLI settings:
----------------
Config file path: /home/vagrant/.st2/config
Client settings:
----------------
ST2_BASE_URL: http://localhost
ST2_AUTH_URL: https://st2express:9100
ST2_API_URL: https://st2express:9101
ST2_AUTH_TOKEN: None

Proxy settings:
---------------
HTTP_PROXY:
HTTPS_PROXY:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2client/shell.py", line 321, in run
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/st2client/commands/resource.py", line 237, in run_and_print
    instances = self.run(args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2client/commands/resource.py", line 41, in decorate
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2client/commands/resource.py", line 259, in run
    return self.manager.get_all(**filters)
  File "/usr/lib/python2.7/dist-packages/st2client/models/core.py", line 35, in decorate
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2client/models/core.py", line 183, in get_all
    response = self.client.get(url=url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2client/utils/httpclient.py", line 33, in decorate
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2client/utils/httpclient.py", line 44, in decorate
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/st2client/utils/httpclient.py", line 68, in get
    response = requests.get(self.root + url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
vagrant@st2express:~$ cat /etc/hosts
# HEADER: This file was autogenerated at 2015-09-15 22:03:16 +0000
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.

# The following lines are desirable for IPv6 capable hosts
127.0.0.1       localhost.localdomain   localhost
172.168.50.11   172.168.50.11   172
vagrant@st2express:~$
```

Manually adding st2express to the hosts file allows `st2` to work from the CLI.

**Comment by jfryman** [comment]
We have since moved to IP based versus hostname. This should no longer be an issue. If you're still seeing things, please do not hesitate to let us know and we'll dig in.
